# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

twerds = ["medium bucks", "karaoke", "what is a javascript", "groovy", "wonkadoodle", "cool beans", "yay cats", "kittens", "vim", "D3 dirtbag", "google glass", "free lunch", "happy hour", "your shit is inherently weak", "blanka", "get drunk", "firebase", "pier concerts", "fruit snacks", "oatmeal", "goldfish", "awesome sauce", "no sleep", "bitcoin", "santa monica", "tic tac toe", "junior developer", "node", "railest", "the fonso", "booty gifs", "sloths", "spaghetti code", "germany", "in the mix", "let us consider", "first things first", "dynamic duo", "fast fingers magoo", "freaky friday" , "super smash bros", "absotively", "jelly beans", "marge simpson", "matching shirt twins", "coffee bean app", "mvp", "angular is not a framework", "php rocks", "rap stack", "mean stack", "d3rp stack", "puppies", "doge", "bootstrap", "air parrot", "command plus it", "fivesquare", "fist to five", "fist of five", "texas", "fun captains", "coworks internet", "frontline rocks", "square cohort", "hippitychat", "shittychat", "dtf", "pizza", "personality test", "introvert", "extrovert", "perceiver", "judger", "empty pivotal tracker", "utah", "chophouse", "postgresappcom", "man stack", "traffic", "quiz time", "chicago", "would you rather", "beerpong champs", "saboteur", "blueberry vodka", "vegas secrets", "blaise’s pool", "england", "20 year old", "green juice", "eat fresh", "deploy early deploy often", "git push", "rollback", "rake db:migrate", "bananas!" , "nested arrays", "instantiate", "crud", "creaaaaaaaaatee", "desssstttrooooyyyy", "rails for dumbasses", "javascript roadtrip", "khoa’s roof", "ng-what?", "no devise", "because rails", "hamatron", "levanye west", "aaahhhhhhhh", "a question was posed in the back", "plug me in", "falling back in chair", "code", "party on some code", "httparty", "let’s hack this shit", "stand ups", "sit downs", "jsón", "mattias’ styling", "barf back at them", "yay", "collaborative notes", "ahuhuh", "god damn air play", "tossing projector in ocean", "abbott kinney", "there’s a gem for that", "indentation", "link table", "dry", "api", "factory girl", "drink all the booze hack all the things", "writing tests", "swag", "leather pants", "back problems", "scalable vector graphics", "sublime text", "groovy", "cool sauce", "quiz time", "lightning talk", "rails", "migrate", "rake routes", "config", "project time", "cool beans", "controller", "model", "view", "angular", "ng-repeat", "party", "code", "git", "merge", "github", "githug", "merge conflict", "co-works", "blank spaces", "meetup", "wdi never ends", "closure", "method", "variable", "function", "parameters", "argument", "params", "console log", "stick that in your asset pipeline and smoke it", "kangular", "local host 3000", "when will the db:drop"]

twerds.each do |x|
	Word.create(word: x)
end
